services:
  corpchat:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        INSTALL_NETBIRD: "false"
    image: pwnbox-ctf
    container_name: corpchat-dev
    ports:
      - "8080:8080"
      - "2222:22"
    volumes:
      - corpchat_data:/data
    environment:
      - FLASK_CONFIG=config.ProductionConfig
      - SECRET_KEY=7x2K#mP9vL4@qR8nWzY3fB6!sDjE1uA5
      - DATABASE_DIR=/data
      - UPLOAD_FOLDER=/data/uploads
      - LOG_DIR=/data/logs
    restart: unless-stopped

  xss-bot:
    build:
      context: ../bot
      dockerfile: dockerfile
    container_name: xss-bot
    depends_on:
      - corpchat
    environment:
      - TARGET_URL=http://corpchat:8080
      - BOT_USER=compliancebot
      - BOT_PASS=C0mpl1anceB0t2026
      - DEBUG_TOKEN=b3b46de0-86e1-4a98-885d-1a85d2bef561
      - POLL_MS=60000
      - CHROMIUM_PATH=/usr/bin/chromium
    restart: unless-stopped

volumes:
  corpchat_data:
